name: Pharo CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  pharo-tests:
    strategy:
      fail-fast: false
      matrix:
        pharo: ["10", "11", "12", "13", "14"]

    uses: demarey/pharo-test-gha/.github/workflows/pharo-test.yml@main
    with:
      pharo-version: "${{ matrix.pharo }}"
      metacello-baseline: "Soup"
      metacello-repository: "src"
      test-packages: "Soup.*"